Server:
  RunMode: debug
  # RunMode: release
  HttpPort: 9010
  ReadTimeout: 60
  WriteTimeout: 60
General:
  LogSavePath: storage/logs
  LogFileName: log
  LogFileExt: .log
  LogMaxSize: 60
  LogMaxAge: 7
  MaxThreads: 100
  MaxTasks: 100
Database:
  # 树兰安吉医院：espacs:Espacs@2020@tcp(172.16.0.7:3306)/espacs?charset=utf8
  # 杭州树兰医院：espacs:espacs@2017@tcp(10.20.32.212:31967)/espacs?charset=utf8
  DBConn: espacs:espacs@2017@tcp(10.20.32.212:31967)/espacs?charset=utf8
  # DBConn: hrp:asdf@123@tcp(10.110.20.133:30664)/espacs?charset=utf8  
  DBType: mysql
  MaxIdleConns: 100
  MaxOpenConns: 100
  MaxLifetime: 60
  # HIS 数据库类型 1:mysql 2:oracle
  HISSqlType: 1
  # mysql数据库配置
  OracleDBType: mysql
  OracleDBConn: espacs:Wowjoy@2018@tcp(172.16.255.26:30117)/ms_qypacs?charset=utf8
  OracleDBView: V_PACS_HZ
  # HIS数据库连接oracle数据库配置
  #OracleDBType: godror
  #OracleDBConn: user="pacs_hz" password="yZLoGA0v" connectString="192.168.10.2:1521/orcl"
  #OracleDBView: V_PACS_HZ
Object:
  # 第三方系统类型: 根据医院编号字典表对应（1.树兰医院，2.酉阳医院）
  InterfaceSystemType: 2
  # 中联HIS接口
  HISURL: http://192.168.10.167:8099/zlhis-recv/pacs
