Server:
  RunMode: debug
  # RunMode: release
  HttpPort: 9010
  ReadTimeout: 60
  WriteTimeout: 60
General:
  LogSavePath: storage/logs
  LogFileName: log
  LogFileExt: .log
  LogMaxSize: 60
  LogMaxAge: 7
  MaxThreads: 100
  MaxTasks: 100
Database:
  # ********************************PACS集成平台数据库配置模块*****************************
  # 数据库公共模块
  DBMaxIdleConns: 100
  DBMaxOpenConns: 100
  DBMaxLifetime: 60
  # ******PACS数据库连接信息******
  PacsDBType: mysql
  PacsDBConn: espacs:espacs@2017@tcp(10.20.32.212:31967)/espacs?charset=utf8

  # 申请单
  # HIS 数据库类型 1:mysql 2:oracle
  HISSqlType: 1
  # HIS数据库连接oracle数据库配置
  #OracleDBType: godror
  #OracleDBConn: user="pacs_hz" password="yZLoGA0v" connectString="192.168.10.2:1521/orcl"
  # ******门诊申请单数据库配置******
  MZApplyDBType: mysql
  MZApplyDBConn: sunzegang:sunzegang@2023@tcp(172.16.255.26:35917)/ms_qypacs?charset=utf8
  # ******住院申请单数据库配置******
  ZYApplyDBType: mysql
  ZYApplyDBConn: sunzegang:sunzegang@2023@tcp(172.16.255.26:35917)/ms_qypacs?charset=utf8
  # ******体检申请单数据库配置******
  TJApplyDBType: mysql
  TJApplyDBConn: sunzegang:sunzegang@2023@tcp(172.16.255.26:35917)/ms_qypacs?charset=utf8

Object:
  # 第三方系统类型: 根据医院编号字典表对应（1.树兰医院，2.酉阳医院）
  InterfaceSystemType: 2
  # 中联HIS接口
  HISURL: http://192.168.10.167:8099/zlhis-recv/pacs